/* Simulated Linux (bash) shell for A+ Core 2 Linux command objectives. */
(function () {
  const VFS = App.VFS;
  const R = App.rand;
  const f = (content, extra) => Object.assign({ __file: true, content }, extra || {});
  const rootFile = (content, mode, extra) => f(content, Object.assign({ owner: "root", group: "root", mode: mode || "rw-r--r--" }, extra || {}));
  const rootDir = (children, mode) => Object.assign({ __owner: "root", __mode: mode || "rwxr-xr-x" }, children);

  App.defaultLinuxWorld = function () {
    return {
      os: "linux",
      fs: new VFS(rootDir({
        home: rootDir({
          student: {
            "notes.txt": "A+ Core 2 Linux commands: ls, pwd, cd, grep, find, chmod, chown, sudo, apt, ps, top, kill, df, du, ip, dig, curl",
            Documents: { "report.txt": "Quarterly report draft.\nTODO: add charts." },
            scripts: { "hello.sh": f("#!/bin/bash\necho \"Hello from a script!\"", { mode: "rw-r--r--" }) },
            ".bashrc": "# ~/.bashrc\nalias ll='ls -alF'"
          }
        }),
        etc: rootDir({
          "hostname": rootFile("ubuntu-lab"),
          "hosts": rootFile("127.0.0.1\tlocalhost\n127.0.1.1\tubuntu-lab\n192.168.1.20\tfileserver"),
          "resolv.conf": rootFile("# Generated by NetworkManager\nnameserver 192.168.1.10\nsearch corp.local"),
          "passwd": rootFile("root:x:0:0:root:/root:/bin/bash\ndaemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin\nwww-data:x:33:33:www-data:/var/www:/usr/sbin/nologin\nstudent:x:1000:1000:Student Tech,,,:/home/student:/bin/bash"),
          "shadow": rootFile("root:*:19700:0:99999:7:::\nstudent:$y$j9T$Qm2...hashed...:19700:0:99999:7:::", "rw-r-----"),
          "fstab": rootFile("# <file system>  <mount point>  <type>  <options>  <dump>  <pass>\nUUID=3f1c2a9e-77b1-4c6e-9d1e-8f0a2b3c4d5e  /  ext4  errors=remount-ro  0  1\nUUID=A1B2-C3D4  /boot/efi  vfat  umask=0077  0  1\n/swapfile  none  swap  sw  0  0"),
          "ssh": rootDir({ "sshd_config": rootFile("Port 22\nPermitRootLogin no\nPasswordAuthentication yes") })
        }),
        var: rootDir({
          log: rootDir({
            "syslog": rootFile(
              "Oct  6 09:12:01 ubuntu-lab systemd[1]: Started Daily apt download activities.\nOct  6 09:14:22 ubuntu-lab kernel: [ 1201.33] e1000: eth0 NIC Link is Up 1000 Mbps Full Duplex\nOct  6 09:20:45 ubuntu-lab cron[811]: (root) CMD (run-parts /etc/cron.hourly)\nOct  6 09:31:07 ubuntu-lab nginx[1422]: error: upstream timed out (110: Connection timed out)\nOct  6 09:33:18 ubuntu-lab kernel: [ 1318.07] EXT4-fs warning (device sda1): ext4_dx_add_entry: Directory index full!\nOct  6 09:40:02 ubuntu-lab systemd[1]: Starting Cleanup of Temporary Directories...\nOct  6 09:52:16 ubuntu-lab nginx[1422]: error: connect() failed (111: Connection refused)", "rw-r-----"),
            "auth.log": rootFile(
              "Oct  6 08:01:12 ubuntu-lab sshd[2011]: Accepted publickey for student from 192.168.1.57 port 50122 ssh2\nOct  6 08:44:51 ubuntu-lab sshd[2098]: Failed password for invalid user admin from 203.0.113.45 port 41822 ssh2\nOct  6 08:44:53 ubuntu-lab sshd[2098]: Failed password for invalid user admin from 203.0.113.45 port 41822 ssh2\nOct  6 08:44:56 ubuntu-lab sshd[2101]: Failed password for root from 203.0.113.45 port 41830 ssh2\nOct  6 08:44:59 ubuntu-lab sshd[2101]: Failed password for root from 203.0.113.45 port 41830 ssh2\nOct  6 09:02:33 ubuntu-lab sudo: student : TTY=pts/0 ; PWD=/home/student ; USER=root ; COMMAND=/usr/bin/apt update\nOct  6 09:15:40 ubuntu-lab sshd[2215]: Failed password for student from 198.51.100.7 port 51900 ssh2\nOct  6 09:15:47 ubuntu-lab sshd[2215]: Accepted password for student from 198.51.100.7 port 51900 ssh2", "rw-r-----"),
            app: rootDir({ "debug.log": rootFile("[DEBUG] verbose trace output...\n[DEBUG] verbose trace output...\n(18 GB of this)", "rw-r--r--", { size: 18.6e9 }) })
          }),
          www: rootDir({ html: rootDir({ "index.html": rootFile("<h1>It works!</h1>") }) })
        }),
        tmp: rootDir({}, "rwxrwxrwt"),
        root: rootDir({ ".bashrc": rootFile("# root bashrc") }, "rwx------"),
        usr: rootDir({ bin: rootDir({}), share: rootDir({}) }),
        bin: rootDir({}),
        opt: rootDir({})
      })),
      cwd: ["home", "student"],
      user: "student",
      hostname: "ubuntu-lab",
      sudoUsed: false,
      suStack: [],
      net: { iface: "eth0", ip: "192.168.1.80", cidr: 24, gw: "192.168.1.1", mac: "08:00:27:4e:66:a1", up: true, internet: true },
      dnsTable: { "comptia.org": "104.18.30.99", "www.comptia.org": "104.18.30.99", "google.com": "142.250.72.14", "fileserver": "192.168.1.20", "archive.ubuntu.com": "91.189.91.82", "dc01.corp.local": "192.168.1.10" },
      dnsWorks: true,
      processes: [
        { pid: 1, user: "root", cpu: 0.0, mem: 0.3, cmd: "/sbin/init" },
        { pid: 412, user: "root", cpu: 0.0, mem: 0.2, cmd: "/lib/systemd/systemd-journald" },
        { pid: 811, user: "root", cpu: 0.0, mem: 0.1, cmd: "/usr/sbin/cron -f" },
        { pid: 902, user: "root", cpu: 0.1, mem: 0.4, cmd: "sshd: /usr/sbin/sshd -D" },
        { pid: 1422, user: "www-data", cpu: 0.3, mem: 1.2, cmd: "nginx: worker process" },
        { pid: 2311, user: "student", cpu: 0.0, mem: 0.2, cmd: "-bash" }
      ],
      services: { ssh: "active", nginx: "active", cron: "active", ufw: "inactive" },
      packages: { installed: ["bash", "coreutils", "nano", "openssh-server", "nginx", "curl"], available: { htop: "3.3.0", nmap: "7.94", tree: "2.1.1", git: "2.43.0", "net-tools": "2.10", vim: "9.1", tcpdump: "4.99" } },
      aptUpdated: false,
      disk: { size: 50e9, base: 29.4e9 },
      history: [],
      flags: {}
    };
  };

  const home = w => w.user === "root" ? ["root"] : ["home", w.user];
  const pathStr = abs => "/" + abs.join("/");
  function cwdDisplay(w) {
    const hm = home(w);
    const c = w.cwd;
    if (c.length >= hm.length && hm.every((s, i) => c[i] === s)) return "~" + (c.length > hm.length ? "/" + c.slice(hm.length).join("/") : "");
    return pathStr(c);
  }
  function parsePath(w, p) {
    if (p === "~" || p.startsWith("~/")) return w.fs.norm([], home(w).concat(p.slice(2).split("/")), true);
    return w.fs.norm(w.cwd, p.split("/"), p.startsWith("/"));
  }
  // permission checks
  function can(w, node, bit) {
    if (w.user === "root") return true;
    const i = { r: 0, w: 1, x: 2 }[bit];
    const m = node.mode || "rwxr-xr-x";
    if (node.owner === w.user) return m[i] !== "-";
    return m[6 + i] !== "-";
  }
  function fileSize(n) { return n.size != null ? n.size : (n.type === "dir" ? 4096 : n.content.length); }
  function usedBytes(w) { let s = 0; w.fs.walk(w.fs.root, [], n => { if (n.type === "file" && n.size) s += n.size; }); return w.disk.base + s; }
  const human = b => b >= 1e9 ? (b / 1e9).toFixed(1).replace(/\.0$/, "") + "G" : b >= 1e6 ? (b / 1e6).toFixed(1).replace(/\.0$/, "") + "M" : b >= 1e3 ? Math.round(b / 1e3) + "K" : String(b);
  const lsDate = () => { const d = new Date(); return d.toLocaleString("en-US", { month: "short" }) + " " + String(d.getDate()).padStart(2) + " " + String(d.getHours()).padStart(2, "0") + ":" + String(d.getMinutes()).padStart(2, "0"); };
  const denied = (io, cmd, p) => io.out(`${cmd}: ${p ? "cannot open '" + p + "' for reading: " : ""}Permission denied`, "t-err");

  const MAN = {
    ls: "ls - list directory contents\n  -l  long listing (permissions, owner, size)\n  -a  include hidden files (dotfiles)\n  -h  human-readable sizes (with -l)",
    cd: "cd - change the shell working directory.  cd ..  (up)  cd ~ (home)  cd / (root)",
    pwd: "pwd - print name of current/working directory",
    chmod: "chmod - change file mode bits\n  chmod 755 file   (rwxr-xr-x)\n  chmod +x file    (add execute)\n  chmod u+x,g-w file\n  r=4 w=2 x=1; digits are owner, group, others",
    chown: "chown - change file owner and group\n  chown user file\n  chown user:group file\n  Usually requires sudo.",
    grep: "grep - print lines that match patterns\n  grep [-i] [-v] [-n] [-r] PATTERN [FILE...]\n  -i ignore case, -v invert match, -n line numbers, -r recursive",
    find: "find - search for files in a directory hierarchy\n  find /path -name \"*.log\"\n  find . -type f -size +100M",
    sudo: "sudo - execute a command as another user (default: root)\n  sudo apt update",
    su: "su - run a shell as another user. 'su -' becomes root (needs root's password); 'exit' to return.",
    apt: "apt - package manager (Debian/Ubuntu)\n  sudo apt update           refresh package lists\n  sudo apt upgrade          install updates\n  sudo apt install PKG      install\n  sudo apt remove PKG       remove",
    dnf: "dnf - package manager (Red Hat/Fedora). dnf install PKG, dnf update, dnf remove PKG",
    ps: "ps - report a snapshot of current processes.  ps aux  (all processes, all users)",
    top: "top - display Linux processes in real time (simulator shows one snapshot).",
    kill: "kill - send a signal to a process\n  kill PID      (SIGTERM 15, polite)\n  kill -9 PID   (SIGKILL, forced)",
    df: "df - report file system disk space usage.  df -h  (human readable)",
    du: "du - estimate file space usage.  du -sh DIR  ;  du -sh /var/log/*",
    ip: "ip - show / manipulate routing, devices\n  ip addr (ip a)   show addresses\n  ip route         show routing table\n  ip link          show interfaces",
    ping: "ping - send ICMP ECHO_REQUEST. Linux pings forever by default; use -c COUNT.",
    dig: "dig - DNS lookup utility.  dig comptia.org  ;  dig comptia.org MX  ;  dig @8.8.8.8 comptia.org",
    curl: "curl - transfer a URL.  curl https://example.com  ;  curl -I URL (headers only)",
    traceroute: "traceroute - print the route packets take to a host",
    cat: "cat - concatenate files and print on the standard output",
    mv: "mv - move (rename) files", cp: "cp - copy files and directories (-r for directories)",
    rm: "rm - remove files or directories (-r recursive, -f force)",
    nano: "nano - a simple text editor (simulator: view-only)",
    man: "man - an interface to the system reference manuals",
    systemctl: "systemctl - control systemd services\n  systemctl status SERVICE\n  sudo systemctl restart SERVICE\n  sudo systemctl enable SERVICE",
    passwd: "passwd - change user password",
    mkdir: "mkdir - make directories (-p creates parents)", touch: "touch - create empty file / update timestamp",
    whoami: "whoami - print effective user name", history: "history - list previously entered commands",
    uname: "uname - print system information (-a for all)", head: "head - output the first lines of files (-n N)", tail: "tail - output the last lines of files (-n N, -f follow)"
  };
  const COMMANDS = ["apt", "apt-get", "cat", "cd", "chmod", "chown", "clear", "cp", "curl", "df", "dig", "dnf", "du", "echo", "exit", "find", "grep", "head", "help",
    "history", "hostname", "id", "ifconfig", "ip", "kill", "less", "ls", "man", "mkdir", "more", "mv", "nano", "nslookup", "passwd", "ping", "ps", "pwd", "rm", "rmdir",
    "su", "sudo", "systemctl", "tail", "top", "touch", "traceroute", "uname", "wc", "whoami"];

  const C = {};
  C.help = (a, io) => io.out("Simulated bash. Commands: " + COMMANDS.join(", ") + "\nUse 'man COMMAND' for help. Pipes (|) to grep/wc/head/tail/sort and redirects (> >>) work.", "t-info");
  C.clear = (a, io) => io.clear();
  C.pwd = (a, io, w) => io.out(pathStr(w.cwd));
  C.whoami = (a, io, w) => io.out(w.user);
  C.id = (a, io, w) => io.out(w.user === "root" ? "uid=0(root) gid=0(root) groups=0(root)" : "uid=1000(student) gid=1000(student) groups=1000(student),4(adm),27(sudo)");
  C.hostname = (a, io, w) => io.out(w.hostname);
  C.uname = (a, io) => io.out(a.includes("-a") ? "Linux ubuntu-lab 6.8.0-45-generic #45-Ubuntu SMP PREEMPT_DYNAMIC x86_64 x86_64 x86_64 GNU/Linux" : "Linux");
  C.echo = (a, io) => io.out(a.join(" "));
  C.history = (a, io, w) => w.history.forEach((h, i) => io.out(String(i + 1).padStart(5) + "  " + h));
  C.man = (a, io) => { if (!a[0]) { io.out("What manual page do you want?\nFor example, try 'man man'."); return; } io.out(MAN[a[0]] ? `${a[0].toUpperCase()}(1)\n\nNAME\n  ${MAN[a[0]]}` : `No manual entry for ${a[0]}`, MAN[a[0]] ? "" : "t-err"); };
  C.exit = (a, io, w) => {
    if (w.suStack.length) { w.user = w.suStack.pop(); w.cwd = home(w); io.out("logout"); return; }
    io.out("(Simulator) This shell stays open — pick another mission or keep practicing.", "t-dim");
  };

  C.cd = (a, io, w) => {
    const p = parsePath(w, a[0] || "~");
    const n = w.fs.get(p);
    if (!n) { io.out(`bash: cd: ${a[0]}: No such file or directory`, "t-err"); return; }
    if (n.type !== "dir") { io.out(`bash: cd: ${a[0]}: Not a directory`, "t-err"); return; }
    if (!can(w, n, "x")) { io.out(`bash: cd: ${a[0]}: Permission denied`, "t-err"); return; }
    w.cwd = p;
  };
  C.ls = (a, io, w) => {
    const flags = a.filter(x => x.startsWith("-")).join("");
    const long = flags.includes("l"), all = flags.includes("a"), hum = flags.includes("h");
    const targets = a.filter(x => !x.startsWith("-"));
    const list = targets.length ? targets : ["."];
    for (const t of list) {
      const p = parsePath(w, t);
      const n = w.fs.get(p);
      if (!n) { io.out(`ls: cannot access '${t}': No such file or directory`, "t-err"); continue; }
      if (n.type === "dir" && !can(w, n, "r")) { io.out(`ls: cannot open directory '${t}': Permission denied`, "t-err"); continue; }
      if (list.length > 1) io.out(t + ":");
      let entries = n.type === "dir" ? Object.values(n.children) : [n];
      if (!all) entries = entries.filter(e => !e.name.startsWith("."));
      entries.sort((x, y) => x.name.localeCompare(y.name));
      if (long) {
        if (n.type === "dir") io.out("total " + entries.length * 4);
        if (all && n.type === "dir") { io.out(`drwxr-xr-x  2 ${n.owner.padEnd(8)} ${n.owner.padEnd(8)} ${"4096".padStart(6)} ${lsDate()} .`); io.out(`drwxr-xr-x  3 root     root     ${"4096".padStart(6)} ${lsDate()} ..`); }
        for (const e of entries) {
          const sz = fileSize(e);
          io.out(`${e.type === "dir" ? "d" : "-"}${e.mode} ${e.type === "dir" ? 2 : 1} ${e.owner.padEnd(8)} ${(e.group || e.owner).padEnd(8)} ${(hum ? human(sz) : String(sz)).padStart(hum ? 5 : 11)} ${lsDate()} ${e.name}`, e.type === "dir" ? "t-dir" : e.mode[2] === "x" ? "t-exe" : "");
        }
      } else {
        const line = (all && n.type === "dir" ? [".", ".."] : []).concat(entries.map(e => e.name));
        if (line.length) io.html(line.map(nm => { const e = n.type === "dir" ? n.children[nm] : n; const cls = e && e.type === "dir" ? "t-dir" : e && e.mode && e.mode[2] === "x" ? "t-exe" : nm === "." || nm === ".." ? "t-dir" : ""; return `<span class="${cls}">${nm.replace(/</g, "&lt;")}</span>`; }).join("  "));
      }
    }
    if (long) w.flags.lsl = true;
  };
  function readFile(w, io, cmd, t) {
    const n = w.fs.get(parsePath(w, t));
    if (!n) { io.out(`${cmd}: ${t}: No such file or directory`, "t-err"); return null; }
    if (n.type === "dir") { io.out(`${cmd}: ${t}: Is a directory`, "t-err"); return null; }
    if (!can(w, n, "r")) { io.out(`${cmd}: ${t}: Permission denied`, "t-err"); return null; }
    return n.content;
  }
  C.cat = C.less = C.more = (a, io, w, cmd) => { if (!a.length) { io.out("(Simulator) cat needs a file name.", "t-dim"); return; } for (const t of a) { const c = readFile(w, io, cmd || "cat", t); if (c != null) io.out(c); } };
  C.nano = C.vi = C.vim = (a, io, w) => {
    if (!a[0]) { io.out("(Simulator) nano needs a file name.", "t-dim"); return; }
    const c = readFile(w, io, "nano", a[0]);
    if (c == null) return;
    io.out(`  GNU nano 7.2                ${a[0]}\n${"-".repeat(50)}`, "t-info");
    io.out(c);
    io.out(`${"-".repeat(50)}\n(Simulator) Editing isn't supported — viewing only. ^X Exit`, "t-dim");
  };
  C.head = C.tail = (a, io, w, cmd) => {
    const ni = a.indexOf("-n"); const n = ni >= 0 ? parseInt(a[ni + 1], 10) : 10;
    const file = a.filter((x, i) => !x.startsWith("-") && i !== ni + 1)[0];
    const c = file && readFile(w, io, cmd, file);
    if (c == null) return;
    const lines = c.split("\n");
    io.out((cmd === "head" ? lines.slice(0, n) : lines.slice(-n)).join("\n"));
  };
  C.touch = (a, io, w) => a.forEach(t => {
    const p = parsePath(w, t);
    if (w.fs.get(p)) return;
    const parent = w.fs.parentOf(p);
    if (!parent) { io.out(`touch: cannot touch '${t}': No such file or directory`, "t-err"); return; }
    if (!can(w, parent, "w")) { io.out(`touch: cannot touch '${t}': Permission denied`, "t-err"); return; }
    w.fs.write(p, ""); const nn = w.fs.get(p); nn.owner = nn.group = w.user;
  });
  C.mkdir = (a, io, w) => {
    const parents = a.includes("-p");
    a.filter(x => !x.startsWith("-")).forEach(t => {
      const p = parsePath(w, t);
      for (let i = parents ? 1 : p.length; i <= p.length; i++) {
        const sub = p.slice(0, i);
        if (w.fs.get(sub)) { if (i === p.length && !parents) io.out(`mkdir: cannot create directory '${t}': File exists`, "t-err"); continue; }
        const parent = w.fs.parentOf(sub);
        if (!parent) { io.out(`mkdir: cannot create directory '${t}': No such file or directory`, "t-err"); return; }
        if (!can(w, parent, "w")) { io.out(`mkdir: cannot create directory '${t}': Permission denied`, "t-err"); return; }
        w.fs.mkdir(sub); const nn = w.fs.get(sub); nn.owner = nn.group = w.user;
      }
    });
  };
  C.rmdir = (a, io, w) => a.forEach(t => {
    const p = parsePath(w, t); const n = w.fs.get(p);
    if (!n || n.type !== "dir") { io.out(`rmdir: failed to remove '${t}': No such file or directory`, "t-err"); return; }
    if (Object.keys(n.children).length) { io.out(`rmdir: failed to remove '${t}': Directory not empty`, "t-err"); return; }
    w.fs.remove(p);
  });
  C.rm = (a, io, w) => {
    const fl = a.filter(x => x.startsWith("-")).join("");
    const rec = /r|R/.test(fl), force = fl.includes("f");
    let targets = [];
    for (const t of a.filter(x => !x.startsWith("-"))) {
      if (/[*?]/.test(t)) {
        const p = parsePath(w, t); const dir = w.fs.get(p.slice(0, -1)); const re = VFS.globToRe(p[p.length - 1]);
        if (dir) Object.values(dir.children).filter(c => re.test(c.name)).forEach(c => targets.push([t, p.slice(0, -1).concat(c.name)]));
      } else targets.push([t, parsePath(w, t)]);
    }
    if (!targets.length) { if (!force) io.out("rm: missing operand", "t-err"); return; }
    for (const [t, p] of targets) {
      const n = w.fs.get(p);
      if (!n) { if (!force) io.out(`rm: cannot remove '${t}': No such file or directory`, "t-err"); continue; }
      if (n.type === "dir" && !rec) { io.out(`rm: cannot remove '${t}': Is a directory`, "t-err"); continue; }
      if (!p.length) { io.out("rm: it is dangerous to operate recursively on '/'\nrm: use --no-preserve-root to override this failsafe", "t-err"); continue; }
      const parent = w.fs.parentOf(p);
      if (!can(w, parent, "w")) { io.out(`rm: cannot remove '${t}': Permission denied`, "t-err"); continue; }
      w.fs.remove(p);
      w.flags.removed = (w.flags.removed || []).concat(pathStr(p));
    }
  };
  function cpmv(a, io, w, move) {
    const name = move ? "mv" : "cp";
    const rec = a.some(x => /^-.*r/i.test(x));
    const args = a.filter(x => !x.startsWith("-"));
    if (args.length < 2) { io.out(`${name}: missing destination file operand`, "t-err"); return; }
    const sp = parsePath(w, args[0]); const src = w.fs.get(sp);
    if (!src) { io.out(`${name}: cannot stat '${args[0]}': No such file or directory`, "t-err"); return; }
    if (src.type === "dir" && !rec && !move) { io.out(`cp: -r not specified; omitting directory '${args[0]}'`, "t-err"); return; }
    if (!can(w, src, "r")) { io.out(`${name}: cannot open '${args[0]}' for reading: Permission denied`, "t-err"); return; }
    const dp = parsePath(w, args[1]); const dn = w.fs.get(dp);
    let parent, nm;
    if (dn && dn.type === "dir") { parent = dn; nm = src.name; } else { parent = w.fs.parentOf(dp); nm = dp[dp.length - 1]; }
    if (!parent) { io.out(`${name}: cannot create regular file '${args[1]}': No such file or directory`, "t-err"); return; }
    if (!can(w, parent, "w")) { io.out(`${name}: cannot create regular file '${args[1]}': Permission denied`, "t-err"); return; }
    const copy = JSON.parse(JSON.stringify(src)); copy.name = nm;
    if (!move) { copy.owner = copy.group = w.user; }
    parent.children[nm] = copy;
    if (move) w.fs.remove(sp);
  }
  C.cp = (a, io, w) => cpmv(a, io, w, false);
  C.mv = (a, io, w) => cpmv(a, io, w, true);

  // permissions
  function applyMode(mode, spec) {
    if (/^[0-7]{3}$/.test(spec)) return spec.split("").map(d => { d = +d; return (d & 4 ? "r" : "-") + (d & 2 ? "w" : "-") + (d & 1 ? "x" : "-"); }).join("");
    const m = mode.split("");
    for (const part of spec.split(",")) {
      const mm = part.match(/^([ugoa]*)([+\-=])([rwx]*)$/);
      if (!mm) return null;
      const who = (mm[1] || "a").replace("a", "ugo");
      for (const wch of who) {
        const base = { u: 0, g: 3, o: 6 }[wch];
        if (mm[2] === "=") for (let i = 0; i < 3; i++) m[base + i] = "-";
        for (const p of mm[3]) { const i = base + "rwx".indexOf(p); m[i] = mm[2] === "-" ? "-" : p; }
      }
    }
    return m.join("");
  }
  C.chmod = (a, io, w) => {
    const args = a.filter(x => x !== "-R");
    if (args.length < 2) { io.out("chmod: missing operand", "t-err"); return; }
    for (const t of args.slice(1)) {
      const n = w.fs.get(parsePath(w, t));
      if (!n) { io.out(`chmod: cannot access '${t}': No such file or directory`, "t-err"); continue; }
      if (w.user !== "root" && n.owner !== w.user) { io.out(`chmod: changing permissions of '${t}': Operation not permitted`, "t-err"); continue; }
      const nm = applyMode(n.mode, args[0]);
      if (!nm) { io.out(`chmod: invalid mode: '${args[0]}'`, "t-err"); return; }
      n.mode = nm;
    }
  };
  C.chown = (a, io, w) => {
    const args = a.filter(x => x !== "-R");
    if (args.length < 2) { io.out("chown: missing operand", "t-err"); return; }
    const [u, g] = args[0].split(":");
    if (!["root", "student", "www-data"].includes(u)) { io.out(`chown: invalid user: '${args[0]}'`, "t-err"); return; }
    for (const t of args.slice(1)) {
      const n = w.fs.get(parsePath(w, t));
      if (!n) { io.out(`chown: cannot access '${t}': No such file or directory`, "t-err"); continue; }
      if (w.user !== "root") { io.out(`chown: changing ownership of '${t}': Operation not permitted`, "t-err"); continue; }
      n.owner = u; if (g) n.group = g;
      if (a.includes("-R") && n.type === "dir") w.fs.walk(n, [], c => { c.owner = u; if (g) c.group = g; });
    }
  };

  // search
  C.grep = (a, io, w, cmd, stdin) => {
    const fl = a.filter(x => /^-[a-zA-Z]+$/.test(x)).join("");
    const ci = fl.includes("i"), inv = fl.includes("v"), num = fl.includes("n"), rec = /r|R/.test(fl), cnt = fl.includes("c");
    const rest = a.filter(x => !/^-[a-zA-Z]+$/.test(x));
    const pat = rest[0];
    if (pat == null) { io.out("Usage: grep [OPTION]... PATTERNS [FILE]...", "t-err"); return; }
    let re;
    try { re = new RegExp(pat, ci ? "i" : ""); } catch (e) { re = new RegExp(pat.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), ci ? "i" : ""); }
    const sources = [];
    if (stdin != null && rest.length < 2) sources.push([null, stdin]);
    for (const t of rest.slice(1)) {
      const p = parsePath(w, t); const n = w.fs.get(p);
      if (!n) { io.out(`grep: ${t}: No such file or directory`, "t-err"); continue; }
      if (n.type === "dir") {
        if (!rec) { io.out(`grep: ${t}: Is a directory`, "t-err"); continue; }
        w.fs.walk(n, p, (c, cp) => { if (c.type === "file") sources.push(can(w, c, "r") ? [pathStr(cp), c.content] : [pathStr(cp), null]); });
      } else sources.push([t, can(w, n, "r") ? n.content : null]);
    }
    const multi = sources.length > 1;
    let total = 0;
    for (const [name, content] of sources) {
      if (content == null) { io.out(`grep: ${name}: Permission denied`, "t-err"); continue; }
      let c = 0;
      content.split("\n").forEach((line, i) => {
        if (re.test(line) !== inv) { c++; if (!cnt) io.out((multi ? name + ":" : "") + (num ? i + 1 + ":" : "") + line, "t-warn"); }
      });
      if (cnt) io.out((multi ? name + ":" : "") + c);
      total += c;
    }
    w.flags.grep = (w.flags.grep || []).concat({ pat, files: rest.slice(1), total, ci });
  };
  C.find = (a, io, w) => {
    const start = a[0] && !a[0].startsWith("-") ? a[0] : ".";
    const ni = a.indexOf("-name"), ii = a.indexOf("-iname"), ti = a.indexOf("-type"), si = a.indexOf("-size");
    const pat = ni >= 0 ? a[ni + 1] : ii >= 0 ? a[ii + 1] : null;
    const re = pat ? VFS.globToRe(pat, ii >= 0) : null;
    const type = ti >= 0 ? a[ti + 1] : null;
    let minSize = null;
    if (si >= 0) { const m = (a[si + 1] || "").match(/^\+(\d+)([kMG]?)$/); if (m) minSize = +m[1] * ({ k: 1e3, M: 1e6, G: 1e9 }[m[2]] || 512); }
    const sp = parsePath(w, start); const root = w.fs.get(sp);
    if (!root) { io.out(`find: '${start}': No such file or directory`, "t-err"); return; }
    const results = [];
    (function walk(n, p) {
      if (n.type === "dir" && !can(w, n, "r")) { io.out(`find: '${pathStr(p)}': Permission denied`, "t-err"); return; }
      const disp = start === "." ? "." + (p.length > sp.length ? "/" + p.slice(sp.length).join("/") : "") : (start.replace(/\/$/, "") + (p.length > sp.length ? "/" + p.slice(sp.length).join("/") : "")).replace(/^\/\//, "/");
      const okName = !re || re.test(n.name);
      const okType = !type || (type === "d" ? n.type === "dir" : n.type === "file");
      const okSize = minSize == null || (n.type === "file" && fileSize(n) > minSize);
      if (okName && okType && okSize) { results.push(disp); io.out(disp); }
      if (n.type === "dir") Object.values(n.children).forEach(c => walk(c, p.concat(c.name)));
    })(root, sp);
    w.flags.find = (w.flags.find || []).concat({ pat, start, minSize, results });
  };
  C.wc = (a, io, w, cmd, stdin) => {
    const text = stdin != null ? stdin : (a.find(x => !x.startsWith("-")) ? readFile(w, io, "wc", a.find(x => !x.startsWith("-"))) : "");
    if (text == null) return;
    const lines = text ? text.split("\n").length : 0;
    if (a.includes("-l")) io.out(String(lines)); else io.out(`${lines} ${text.split(/\s+/).filter(Boolean).length} ${text.length}`);
  };

  // processes
  C.ps = (a, io, w) => {
    if (!a.length) { io.out("    PID TTY          TIME CMD\n   2311 pts/0    00:00:00 bash\n   " + R(3000, 3999) + " pts/0    00:00:00 ps"); return; }
    io.out("USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND");
    w.processes.forEach(p => io.out(`${p.user.padEnd(10)} ${String(p.pid).padStart(6)} ${p.cpu.toFixed(1).padStart(4)} ${p.mem.toFixed(1).padStart(4)} ${String(R(10000, 900000)).padStart(6)} ${String(R(1000, 90000)).padStart(5)} ?        ${p.cpu > 50 ? "R" : "S"}    09:00   ${p.cpu > 50 ? "42:17" : "0:01"} ${p.cmd}`, p.cpu > 50 ? "t-warn" : ""));
    w.flags.ps = true;
  };
  C.top = (a, io, w) => {
    const load = w.processes.reduce((s, p) => s + p.cpu, 0) / 100;
    io.out(`top - ${new Date().toTimeString().slice(0, 8)} up 3:12,  1 user,  load average: ${load.toFixed(2)}, ${(load * 0.9).toFixed(2)}, ${(load * 0.7).toFixed(2)}\nTasks: ${w.processes.length + 120} total,   ${w.processes.filter(p => p.cpu > 50).length + 1} running\n%Cpu(s): ${Math.min(99.9, w.processes.reduce((s, p) => s + p.cpu, 0) / 2).toFixed(1)} us,  1.2 sy,  0.0 ni\nMiB Mem :   7951.2 total,   3120.4 free,   2410.8 used,   2420.0 buff/cache\n\n    PID USER      PR  NI    VIRT    RES  %CPU  %MEM     TIME+ COMMAND`);
    w.processes.slice().sort((x, y) => y.cpu - x.cpu).forEach(p => io.out(`${String(p.pid).padStart(7)} ${p.user.padEnd(9)} 20   0 ${String(R(10000, 900000)).padStart(7)} ${String(R(1000, 90000)).padStart(6)} ${p.cpu.toFixed(1).padStart(5)} ${p.mem.toFixed(1).padStart(5)} ${p.cpu > 50 ? " 42:17.03" : "  0:01.10"} ${p.cmd.split(" ")[0].split("/").pop()}`, p.cpu > 50 ? "t-warn" : ""));
    io.out("\n(Simulator: one snapshot shown. In real top press q to quit, k to kill.)", "t-dim");
    w.flags.top = true;
  };
  C.htop = (a, io, w) => {
    if (!w.packages.installed.includes("htop")) { io.out("Command 'htop' not found, but can be installed with:\nsudo apt install htop", "t-err"); return; }
    io.out("  CPU[|||||                 12.4%]   Tasks: 126, 1 running\n  Mem[||||||||||        2.41G/7.76G]   Load average: 0.21 0.18 0.11\n\n  PID USER      PRI  NI  CPU% MEM%   Command", "t-ok");
    w.processes.forEach(p => io.out(`${String(p.pid).padStart(5)} ${p.user.padEnd(9)}  20   0 ${p.cpu.toFixed(1).padStart(5)} ${p.mem.toFixed(1).padStart(4)}   ${p.cmd}`));
    io.out("\n(Simulator snapshot — F10 to quit in the real thing)", "t-dim");
    w.flags.htop = true;
  };
  C.kill = (a, io, w) => {
    const sig9 = a.includes("-9") || a.includes("-KILL") || a.includes("-SIGKILL");
    const pids = a.filter(x => /^\d+$/.test(x)).map(Number);
    if (!pids.length) { io.out("kill: usage: kill [-s sigspec | -n signum | -sigspec] pid", "t-err"); return; }
    for (const pid of pids) {
      const p = w.processes.find(x => x.pid === pid);
      if (!p) { io.out(`bash: kill: (${pid}) - No such process`, "t-err"); continue; }
      if (w.user !== "root" && p.user !== w.user) { io.out(`bash: kill: (${pid}) - Operation not permitted`, "t-err"); continue; }
      if (p.ignoresTerm && !sig9) { w.flags.triedTerm = true; continue; } // silently ignored, like a stuck process
      w.processes = w.processes.filter(x => x !== p);
      w.flags.killed = (w.flags.killed || []).concat(pid);
    }
  };
  C.systemctl = (a, io, w) => {
    const [act, svcRaw] = a; const svc = (svcRaw || "").replace(/\.service$/, "");
    if (!act || !svc) { io.out("Usage: systemctl [status|start|stop|restart|enable|disable] SERVICE", "t-err"); return; }
    if (!(svc in w.services)) { io.out(`Unit ${svc}.service could not be found.`, "t-err"); return; }
    if (act === "status") {
      const st = w.services[svc];
      io.out(`● ${svc}.service\n     Loaded: loaded (/lib/systemd/system/${svc}.service; enabled)\n     Active: ${st === "active" ? "active (running)" : st === "failed" ? "failed (Result: exit-code)" : "inactive (dead)"} since ${new Date().toDateString()}`, st === "active" ? "t-ok" : "t-err");
      return;
    }
    if (w.user !== "root") { io.out("==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ====\nAuthentication is required to manage system services or units.\nFailed to " + act + " " + svc + ".service: Access denied (try sudo)", "t-err"); return; }
    if (act === "start" || act === "restart") w.services[svc] = "active";
    if (act === "stop") w.services[svc] = "inactive";
    w.flags["svc-" + act] = svc;
  };

  // disk
  C.df = (a, io, w) => {
    const hu = a.includes("-h");
    const used = usedBytes(w), size = w.disk.size, avail = size - used, pct = Math.round((used / size) * 100);
    const fmt = b => hu ? human(b) : String(Math.round(b / 1024));
    io.out(`Filesystem     ${hu ? " Size  Used Avail" : "1K-blocks     Used Available"} Use% Mounted on`);
    io.out(`tmpfs          ${hu ? "  794M  1.6M  792M" : "   813020     1640    811380"}   1% /run`);
    io.out(`/dev/sda2      ${hu ? fmt(size).padStart(5) + " " + fmt(used).padStart(5) + " " + fmt(avail).padStart(5) : fmt(size).padStart(9) + " " + fmt(used).padStart(8) + " " + fmt(avail).padStart(9)} ${(pct + "%").padStart(4)} /`, pct > 90 ? "t-err" : "");
    io.out(`/dev/sda1      ${hu ? "  1.1G  6.1M  1.1G" : "  1098632     6220   1092412"}   1% /boot/efi`);
    w.flags.df = (w.flags.df || 0) + 1;
    w.flags.dfPct = pct;
  };
  C.du = (a, io, w) => {
    const hu = a.includes("-h") || a.some(x => /^-.*h/.test(x));
    const summarize = a.some(x => /^-.*s/.test(x));
    let targets = a.filter(x => !x.startsWith("-"));
    if (!targets.length) targets = ["."];
    const expanded = [];
    for (const t of targets) {
      if (/[*?]/.test(t)) { const p = parsePath(w, t); const dir = w.fs.get(p.slice(0, -1)); const re = VFS.globToRe(p[p.length - 1]); if (dir) Object.values(dir.children).filter(c => re.test(c.name)).forEach(c => expanded.push((t.replace(/\/[^/]*$/, "") + "/" + c.name))); }
      else expanded.push(t);
    }
    for (const t of expanded) {
      const n = w.fs.get(parsePath(w, t));
      if (!n) { io.out(`du: cannot access '${t}': No such file or directory`, "t-err"); continue; }
      if (n.type === "dir" && !can(w, n, "r")) { io.out(`du: cannot read directory '${t}': Permission denied`, "t-err"); continue; }
      let s = 0; w.fs.walk(n, [], c => { s += c.type === "file" ? fileSize(c) : 4096; });
      if (!summarize && n.type === "dir") Object.values(n.children).filter(c => c.type === "dir").forEach(c => { let cs = 0; w.fs.walk(c, [], x => { cs += x.type === "file" ? fileSize(x) : 4096; }); io.out(`${hu ? human(cs) : Math.round(cs / 1024)}\t${t}/${c.name}`); });
      io.out(`${hu ? human(s) : Math.round(s / 1024)}\t${t}`, s > 1e9 ? "t-warn" : "");
    }
    w.flags.du = true;
  };

  // packages
  C.apt = C["apt-get"] = async (a, io, w) => {
    const sub = a[0];
    if (!sub) { io.out(MAN.apt); return; }
    if (["update", "upgrade", "install", "remove", "purge"].includes(sub) && w.user !== "root") {
      io.out("E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)\nE: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?", "t-err");
      w.flags.aptDenied = true;
      return;
    }
    if (sub === "update") {
      for (const l of ["Hit:1 http://archive.ubuntu.com/ubuntu noble InRelease", "Get:2 http://archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]", "Get:3 http://security.ubuntu.com/ubuntu noble-security InRelease [126 kB]", "Fetched 252 kB in 1s (210 kB/s)", "Reading package lists... Done", "Building dependency tree... Done", "3 packages can be upgraded. Run 'apt list --upgradable' to see them."]) { await io.sleep(250); io.out(l); }
      w.aptUpdated = true; return;
    }
    if (sub === "upgrade") { io.out("Reading package lists... Done\nCalculating upgrade... Done\nThe following packages will be upgraded:\n  libssl3 openssl tzdata\n3 upgraded, 0 newly installed, 0 to remove and 0 not upgraded."); await io.sleep(800); io.out("Setting up openssl ... Done", "t-ok"); w.flags.upgraded = true; return; }
    if (sub === "install") {
      const pk = a.slice(1).filter(x => !x.startsWith("-"));
      if (!pk.length) { io.out("E: No packages specified", "t-err"); return; }
      io.out("Reading package lists... Done\nBuilding dependency tree... Done");
      for (const p of pk) {
        if (w.packages.installed.includes(p)) { io.out(`${p} is already the newest version.`); continue; }
        if (!w.packages.available[p]) { io.out(`E: Unable to locate package ${p}`, "t-err"); continue; }
        if (!w.aptUpdated && w.requireAptUpdate) { io.out(`E: Unable to locate package ${p}\n(Hint: the package lists are stale — run 'sudo apt update' first.)`, "t-err"); continue; }
        io.out(`The following NEW packages will be installed:\n  ${p}\nGet:1 http://archive.ubuntu.com/ubuntu noble/main amd64 ${p} amd64 ${w.packages.available[p]} [${R(80, 900)} kB]`);
        await io.sleep(700);
        io.out(`Unpacking ${p} (${w.packages.available[p]}) ...\nSetting up ${p} (${w.packages.available[p]}) ...`, "t-ok");
        w.packages.installed.push(p);
      }
      return;
    }
    if (sub === "remove" || sub === "purge") {
      for (const p of a.slice(1)) { if (!w.packages.installed.includes(p)) { io.out(`Package '${p}' is not installed, so not removed`); continue; } w.packages.installed = w.packages.installed.filter(x => x !== p); io.out(`Removing ${p} ...`, "t-ok"); }
      return;
    }
    if (sub === "list") { w.packages.installed.forEach(p => io.out(`${p}/noble,now installed`)); return; }
    if (sub === "search") { Object.keys(w.packages.available).filter(p => p.includes(a[1] || "")).forEach(p => io.out(`${p}/noble ${w.packages.available[p]} amd64`)); return; }
    io.out(`E: Invalid operation ${sub}`, "t-err");
  };
  C.dnf = C.yum = (a, io) => io.out("bash: dnf: command not found\n(This is an Ubuntu/Debian system — use apt. dnf/yum are for Red Hat-based distros like Fedora, RHEL and Rocky.)", "t-err");

  // network
  C.ip = (a, io, w) => {
    const sub = (a[0] || "").toLowerCase();
    const n = w.net;
    if (["a", "addr", "address"].includes(sub)) {
      io.out(`1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN\n    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00\n    inet 127.0.0.1/8 scope host lo`);
      io.out(`2: ${n.iface}: <BROADCAST,MULTICAST${n.up ? ",UP,LOWER_UP" : ""}> mtu 1500 qdisc fq_codel state ${n.up ? "UP" : "DOWN"}\n    link/ether ${n.mac} brd ff:ff:ff:ff:ff:ff` + (n.up && n.ip ? `\n    inet ${n.ip}/${n.cidr} brd 192.168.1.255 scope global dynamic ${n.iface}\n    inet6 fe80::a00:27ff:fe4e:66a1/64 scope link` : ""));
      w.flags.ipaddr = true; return;
    }
    if (["r", "route"].includes(sub)) { io.out(n.up ? `default via ${n.gw} dev ${n.iface} proto dhcp metric 100\n192.168.1.0/24 dev ${n.iface} proto kernel scope link src ${n.ip}` : ""); w.flags.iproute = true; return; }
    if (sub === "link") {
      if (a[1] === "set") {
        if (w.user !== "root") { io.out("RTNETLINK answers: Operation not permitted", "t-err"); return; }
        if (a.includes("up")) { n.up = true; w.flags.linkUp = true; } else if (a.includes("down")) n.up = false;
        return;
      }
      io.out(`1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN\n2: ${n.iface}: <BROADCAST,MULTICAST${n.up ? ",UP,LOWER_UP" : ""}> mtu 1500 state ${n.up ? "UP" : "DOWN"}\n    link/ether ${n.mac}`);
      return;
    }
    io.out("Usage: ip [ OPTIONS ] OBJECT { COMMAND | help }\nwhere  OBJECT := { address | route | link | neigh }", "t-err");
  };
  C.ifconfig = (a, io, w) => {
    if (!w.packages.installed.includes("net-tools")) { io.out("Command 'ifconfig' not found, but can be installed with:\nsudo apt install net-tools\n(Tip: modern distros use 'ip addr' instead.)", "t-err"); return; }
    io.out(`${w.net.iface}: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500\n        inet ${w.net.ip}  netmask 255.255.255.0  broadcast 192.168.1.255\n        ether ${w.net.mac}  txqueuelen 1000  (Ethernet)`);
  };
  function resolveL(w, name) {
    if (/^\d+\.\d+\.\d+\.\d+$/.test(name)) return name;
    if (!w.net.up || !w.dnsWorks) return null;
    return w.dnsTable[name.toLowerCase()] || null;
  }
  function reachL(w, ip) {
    if (!w.net.up) return false;
    if (ip.startsWith("127.") || ip === w.net.ip) return true;
    if (ip.startsWith("192.168.1.")) return ["192.168.1.1", "192.168.1.10", "192.168.1.20"].includes(ip);
    return w.net.internet;
  }
  C.ping = async (a, io, w) => {
    const ci = a.indexOf("-c");
    const count = ci >= 0 ? Math.min(10, parseInt(a[ci + 1], 10) || 4) : 4;
    const target = a.filter((x, i) => !x.startsWith("-") && i !== ci + 1).pop();
    if (!target) { io.out("ping: usage error: Destination address required", "t-err"); return; }
    const ip = resolveL(w, target);
    if (!w.net.up && !/^127\./.test(target)) { io.out("ping: connect: Network is unreachable", "t-err"); return; }
    if (!ip) { io.out(`ping: ${target}: Temporary failure in name resolution`, "t-err"); w.flags.dnsFail = true; return; }
    io.out(`PING ${target} (${ip}) 56(84) bytes of data.`);
    let ok = 0; const times = [];
    for (let i = 1; i <= count; i++) {
      await io.sleep(400);
      if (reachL(w, ip)) { const t = ip.startsWith("192.168.") || ip.startsWith("127.") ? (Math.random() * 2 + .2) : (Math.random() * 20 + 12); times.push(t); ok++; io.out(`64 bytes from ${ip}: icmp_seq=${i} ttl=${ip.startsWith("192.168.") ? 64 : 117} time=${t.toFixed(1)} ms`); }
      else if (i === count) io.out(`From ${w.net.ip} icmp_seq=${i} Destination Host Unreachable`, "t-err");
    }
    if (ci < 0) io.out("^C   (simulator: Linux ping runs until Ctrl+C — use -c 4 next time!)", "t-dim");
    io.out(`\n--- ${target} ping statistics ---\n${count} packets transmitted, ${ok} received, ${Math.round(((count - ok) / count) * 100)}% packet loss, time ${count * 1000}ms`);
    if (times.length) io.out(`rtt min/avg/max/mdev = ${Math.min(...times).toFixed(3)}/${(times.reduce((x, y) => x + y, 0) / times.length).toFixed(3)}/${Math.max(...times).toFixed(3)}/0.412 ms`);
    w.flags.ping = (w.flags.ping || []).concat({ target, ok });
  };
  C.dig = async (a, io, w) => {
    const server = (a.find(x => x.startsWith("@")) || "").slice(1);
    const rest = a.filter(x => !x.startsWith("@") && !x.startsWith("+"));
    const name = rest[0];
    const type = (rest[1] || "A").toUpperCase();
    if (!name) { io.out("(Simulator) usage: dig [@server] name [type]", "t-dim"); return; }
    await io.sleep(300);
    const usedServer = server || (w.fs.get(["etc", "resolv.conf"]).content.match(/nameserver\s+(\S+)/) || [])[1] || "127.0.0.53";
    const working = w.net.up && (server ? server !== w.badDns : w.dnsWorks);
    io.out(`\n; <<>> DiG 9.18.28-0ubuntu0.24.04.1-Ubuntu <<>> ${a.join(" ")}\n;; global options: +cmd`);
    if (!working) { io.out(`;; communications error to ${usedServer}#53: timed out\n;; no servers could be reached`, "t-err"); w.flags.digFail = true; return; }
    const ip = w.dnsTable[name.toLowerCase()];
    io.out(`;; Got answer:\n;; ->>HEADER<<- opcode: QUERY, status: ${ip ? "NOERROR" : "NXDOMAIN"}, id: ${R(1000, 65000)}\n\n;; QUESTION SECTION:\n;${name}.\t\t\tIN\t${type}\n`);
    if (ip) {
      io.out(";; ANSWER SECTION:");
      if (type === "MX") io.out(`${name}.\t\t300\tIN\tMX\t10 mail.${name}.`);
      else if (type === "TXT") io.out(`${name}.\t\t300\tIN\tTXT\t"v=spf1 include:_spf.google.com ~all"`);
      else if (type === "AAAA") io.out(`${name}.\t\t300\tIN\tAAAA\t2606:4700::6812:1e63`);
      else io.out(`${name}.\t\t300\tIN\tA\t${ip}`);
    }
    io.out(`\n;; Query time: ${R(8, 40)} msec\n;; SERVER: ${usedServer}#53(${usedServer}) (UDP)\n;; WHEN: ${new Date().toUTCString()}`);
    w.flags.dig = (w.flags.dig || []).concat({ name, server, ok: !!ip });
  };
  C.nslookup = async (a, io, w) => {
    const ip = resolveL(w, a[0] || "");
    if (!a[0]) { io.out("(Simulator) usage: nslookup name", "t-dim"); return; }
    if (!ip) { io.out(";; connection timed out; no servers could be reached", "t-err"); return; }
    io.out(`Server:\t\t192.168.1.10\nAddress:\t192.168.1.10#53\n\nNon-authoritative answer:\nName:\t${a[0]}\nAddress: ${ip}`);
  };
  C.curl = async (a, io, w) => {
    const url = a.find(x => !x.startsWith("-"));
    if (!url) { io.out("curl: try 'curl --help' or 'curl --manual' for more information", "t-err"); return; }
    const host = url.replace(/^\w+:\/\//, "").split(/[/:]/)[0];
    const ip = resolveL(w, host);
    await io.sleep(500);
    if (!ip) { io.out(`curl: (6) Could not resolve host: ${host}`, "t-err"); return; }
    if (!reachL(w, ip)) { io.out(`curl: (28) Failed to connect to ${host} port 443 after 10001 ms: Timeout was reached`, "t-err"); return; }
    if (a.includes("-I")) io.out(`HTTP/2 200\ncontent-type: text/html; charset=UTF-8\nserver: cloudflare\ndate: ${new Date().toUTCString()}`);
    else io.out(`<!DOCTYPE html>\n<html><head><title>${host}</title></head>\n<body>Welcome to ${host}</body></html>`);
    w.flags.curl = host;
  };
  C.traceroute = async (a, io, w) => {
    const t = a.find(x => !x.startsWith("-"));
    const ip = t && resolveL(w, t);
    if (!ip) { io.out(`${t || ""}: Name or service not known\nCannot handle "host" cmdline arg \`${t || ""}' on position 1 (argc 1)`, "t-err"); return; }
    io.out(`traceroute to ${t} (${ip}), 30 hops max, 60 byte packets`);
    const hops = ["192.168.1.1", "10.20.0.1", "68.85.112.33", "96.110.40.13", ip];
    for (let i = 0; i < hops.length; i++) { await io.sleep(350); const b = 1 + i * 5; io.out(` ${i + 1}  ${hops[i]} (${hops[i]})  ${(b + Math.random() * 3).toFixed(3)} ms  ${(b + Math.random() * 3).toFixed(3)} ms  ${(b + Math.random() * 3).toFixed(3)} ms`); }
  };
  C.passwd = (a, io, w) => {
    if (a[0] && w.user !== "root") { io.out("passwd: You may not view or modify password information for " + a[0] + ".", "t-err"); return; }
    io.out(`Changing password for ${a[0] || w.user}.\n${w.user === "root" ? "" : "Current password: \n"}New password: \nRetype new password: \npasswd: password updated successfully`, "t-ok");
    io.out("(Simulator: password prompts are auto-filled.)", "t-dim");
  };

  // user switching
  C.su = (a, io, w) => {
    const target = a.filter(x => x !== "-")[0] || "root";
    io.out("Password: ");
    if (target === "root") { io.out("su: Authentication failure\n(Tip: on Ubuntu the root account is locked. Use 'sudo -i' or prefix commands with sudo.)", "t-err"); return; }
    io.out("su: user " + target + " does not exist or the user entry does not contain all the required fields", "t-err");
  };

  // ---------- Dispatcher with sudo, pipes, redirects, ./scripts ----------
  async function runCmd(tokens, io, w, stdin) {
    if (!tokens.length) return;
    let cmd = tokens[0];
    let args = tokens.slice(1);
    if (cmd === "sudo") {
      if (args[0] === "-i" || args[0] === "su") {
        if (!w.sudoUsed) { io.out(`[sudo] password for ${w.user}: `); io.out("(Simulator: password accepted)", "t-dim"); w.sudoUsed = true; }
        w.suStack.push(w.user); w.user = "root"; w.cwd = ["root"]; return;
      }
      if (!args.length) { io.out("usage: sudo command", "t-err"); return; }
      if (w.user !== "root" && !w.sudoUsed) { io.out(`[sudo] password for ${w.user}: `); io.out("(Simulator: password accepted)", "t-dim"); w.sudoUsed = true; }
      const prev = w.user; w.user = "root";
      w.flags.sudo = (w.flags.sudo || []).concat(args.join(" "));
      try { await runCmd(args, io, w, stdin); } finally { if (w.user === "root") w.user = prev; }
      return;
    }
    // execute scripts: ./file or bash file / sh file
    if (cmd.startsWith("./") || cmd.startsWith("/") && !C[cmd] || cmd === "bash" || cmd === "sh") {
      const path = cmd === "bash" || cmd === "sh" ? args[0] : cmd;
      if (!path) { io.out("(Simulator) Interactive sub-shells are not supported.", "t-dim"); return; }
      const n = w.fs.get(parsePath(w, path));
      if (!n) { io.out(`bash: ${path}: No such file or directory`, "t-err"); return; }
      if (n.type === "dir") { io.out(`bash: ${path}: Is a directory`, "t-err"); return; }
      if (cmd.startsWith(".") || cmd.startsWith("/")) { if (!can(w, n, "x")) { io.out(`bash: ${path}: Permission denied`, "t-err"); w.flags.execDenied = true; return; } }
      else if (!can(w, n, "r")) { io.out(`${cmd}: ${path}: Permission denied`, "t-err"); return; }
      for (const line of n.content.split("\n")) { const m = line.match(/^\s*echo\s+"?(.*?)"?\s*$/); if (m) io.out(m[1]); }
      w.flags.ranScript = (w.flags.ranScript || []).concat(n.name);
      if (n.onRun) n.onRun(w, io);
      return;
    }
    const fn = C[cmd];
    if (!fn) {
      const known = { ipconfig: "ip addr", cls: "clear", dir: "ls", tracert: "traceroute", tasklist: "ps aux", taskkill: "kill", copy: "cp", move: "mv", del: "rm", type: "cat" };
      io.out(`${cmd}: command not found` + (known[cmd.toLowerCase()] ? `\n(Tip: that's a Windows command. On Linux try '${known[cmd.toLowerCase()]}'.)` : ""), "t-err");
      return;
    }
    await fn(args, io, w, cmd, stdin);
  }
  function splitTop(line, sep) {
    const parts = []; let cur = "", q = null;
    for (const ch of line) { if (q) { if (ch === q) q = null; cur += ch; continue; } if (ch === '"' || ch === "'") { q = ch; cur += ch; continue; } if (ch === sep) { parts.push(cur); cur = ""; } else cur += ch; }
    parts.push(cur); return parts.map(s => s.trim());
  }
  async function exec(line, io, w) {
    if (line.trim()) w.history.push(line.trim());
    for (const seg of splitTop(line, ";")) await execOne(seg, io, w);
  }
  async function execOne(line, io, w) {
    if (!line.trim()) return;
    // && chains
    if (line.includes("&&")) { for (const part of line.split("&&")) await execOne(part, io, w); return; }
    let redirect = null;
    const rm = line.match(/^(.*?)\s*(>>?)\s*([^>|]+)$/);
    if (rm && !/["']/.test(rm[3])) { line = rm[1]; redirect = { append: rm[2] === ">>", path: rm[3].trim() }; }
    const stages = splitTop(line, "|");
    if (stages.length === 1 && !redirect) return runCmd(App.tokenize(stages[0]), io, w);
    let data = null;
    for (let i = 0; i < stages.length; i++) {
      const lines = [];
      const cap = Object.assign({}, io, { out: (t, c) => { if (c === "t-err" || c === "t-dim") io.out(t, c); else lines.push(String(t)); }, html: m => lines.push(m.replace(/<[^>]+>/g, "")), sleep: () => Promise.resolve() });
      const toks = App.tokenize(stages[i]);
      if (["sort", "uniq"].includes(toks[0])) { let ls = (data || "").split("\n"); if (toks[0] === "sort") ls.sort(); else ls = ls.filter((l, j) => l !== ls[j - 1]); lines.push(ls.join("\n")); }
      else if (["head", "tail"].includes(toks[0]) && data != null && !toks.slice(1).some(x => !x.startsWith("-") && !/^\d+$/.test(x))) {
        const ni = toks.indexOf("-n"); const n = ni >= 0 ? parseInt(toks[ni + 1], 10) : 10; const ls = data.split("\n");
        lines.push((toks[0] === "head" ? ls.slice(0, n) : ls.slice(-n)).join("\n"));
      } else await runCmd(toks, cap, w, data);
      data = lines.join("\n");
    }
    if (redirect) {
      const p = parsePath(w, redirect.path);
      const parent = w.fs.parentOf(p); const existing = w.fs.get(p);
      if (!parent) { io.out(`bash: ${redirect.path}: No such file or directory`, "t-err"); return; }
      if ((existing && !can(w, existing, "w")) || (!existing && !can(w, parent, "w"))) { io.out(`bash: ${redirect.path}: Permission denied`, "t-err"); return; }
      w.fs.write(p, (redirect.append && existing ? "\n" : "") + data, redirect.append);
      if (!existing) { const nn = w.fs.get(p); nn.owner = nn.group = w.user; }
      return;
    }
    if (data) io.out(data, "t-warn");
  }

  App.LinuxOS = {
    name: "linux",
    cls: "linux",
    title: "student@ubuntu-lab: ~",
    commands: COMMANDS.concat(["htop", "sudo"]),
    banner: () => [["Welcome to Ubuntu 24.04.1 LTS (GNU/Linux 6.8.0-45-generic x86_64)"], [""], ["Type 'help' for available commands, 'man <command>' for help on one.", "t-dim"], [""]],
    prompt: w => [[`${w.user}@${w.hostname}`, "t-prompt-l"], [":", ""], [cwdDisplay(w), "t-prompt-p"], [w.user === "root" ? "# " : "$ ", ""]],
    exec,
    complete(w, partial) {
      const i = partial.lastIndexOf("/");
      const dirPart = i >= 0 ? partial.slice(0, i + 1) : "";
      const last = i >= 0 ? partial.slice(i + 1) : partial;
      const dir = w.fs.get(parsePath(w, dirPart || "."));
      if (!dir || dir.type !== "dir") return [];
      return Object.values(dir.children).filter(c => c.name.startsWith(last)).map(c => dirPart + c.name + (c.type === "dir" ? "/" : ""));
    }
  };
})();
